name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete existing gh-pages branch
        run: git branch -D gh-pages || true

      - name: Create gh-pages branch
        run: git checkout --orphan gh-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit built files
        run: git add -f dist && git commit -m "Deploy to GitHub Pages"

      - name: Push to GitHub Pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
