name: deploy gh-pages via ssh

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Say Hello World
        run: echo "Hello world!"
