name: build and push to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "MKmoolooo@yandex.ru"

      - name: Delete existing gh-pages branch
        run: git branch -D gh-pages || true

      - name: Create gh-pages branch
        run: git checkout --orphan gh-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit built files
        run: git --work-tree dist add --all && git --work-tree dist commit -m "Deploy ${GITHUB_SHA}"

      - name: Push to GitHub Pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: List all files in the current branch
        run: ls -la
        
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_USER: ${{ secrets.SERVER_SSH_USER }}
          REMOTE_HOST: ${{ secrets.SERVER_SSH_IP }}
          TARGET: /var/www/podderzhka_site
