name: deploy to gh-pages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Upload static files as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: pages
          path: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: podderzhka.co
